services:
  backend:
    build:
      context: ./backend
    container_name: backend
    command:
      bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/home/digitallive
      - ./stream:/opt/data/hls
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - memcached
      - postgres
    env_file:
      - ./docker.env
  celery:
    build:
      context: ./backend
    container_name: celery
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend:/home/digitallive
      - ./stream:/opt/data/hls
    depends_on:
      - redis
    env_file:
      - ./docker.env
  nginx:
    image: alfg/nginx-rtmp
    container_name: nginx_rtmp
    ports:
      - "1935:1935"   # RTMP
      - "8080:80"     # HLS playback
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./nginx/access.log:/var/log/nginx/access.log
      - ./nginx/error.log:/var/log/nginx/error.log
      - ./stream:/opt/data/hls
    depends_on:
      - backend
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - "11211:11211"
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    environment:
      POSTGRES_DB: ${DB_NAME:-test}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}


volumes:
  postgres_data:
