services:
  gunicorn:
    build:
      context: ./backend
    container_name: gunicorn
    command:
      bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && gunicorn -c conf/gunicorn_conf.py core.wsgi:application"
    volumes:
      - ./backend:/home/digitallive
      - ./stream:/opt/data/hls
      - ./cert/:/home/digitallive/cert
    expose:
      - 8000
    depends_on:
      - redis
      - memcached
      - postgres
    env_file:
      - ./docker.env
  daphne:
    build:
      context: ./backend
    container_name: daphne
    command:
      bash -c "daphne -b 0.0.0.0 -p 8001 core.asgi:application"
    volumes:
      - ./backend:/home/digitallive
      - ./stream:/opt/data/hls
      - ./cert/:/home/digitallive/cert
    expose:
      - 8001
    depends_on:
      - redis
      - memcached
      - postgres
      - gunicorn
    env_file:
      - ./docker.env
  celery:
    build:
      context: ./backend
    container_name: celery
    command: celery -A core worker --loglevel=info
    volumes:
      - ./backend:/home/digitallive
      - ./stream:/opt/data/hls
    depends_on:
      - redis
    env_file:
      - ./docker.env
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "1935:1935"   # RTMP
#      - "8080:80"     # HLS playback
      - "80:80"
      - "443:443"
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/access.log:/var/log/nginx/access.log
#      - ./nginx/error.log:/var/log/nginx/error.log
      - ./cert/:/home/digitallive/cert
      - ./backend/staticfiles:/home/digitallive/staticfiles
      - ./backend/media:/home/digitallive/media
      - ./stream:/opt/data/hls
    depends_on:
      - gunicorn
      - daphne
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  memcached:
    image: memcached:alpine
    container_name: memcached
    ports:
      - "11211:11211"
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    environment:
      POSTGRES_DB: ${DB_NAME:-test}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}


volumes:
  postgres_data:
