# Generated by Django 5.1.7 on 2025-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_display_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='loop',
            field=models.IntegerField(default=0, help_text='-1 means unlimited and 0 mean 1 time', verbose_name='Number of times to play'),
        ),
    ]
